$('#Ilya').typeIt({
     speed: 75,
     autoStart: true
})
.tiType("Дорогой Илья!")
.tiPause(2000)
.tiBreak()
.tiBreak()
.tiType("Ну вот и наша игра подошла к концу ")
.tiPause(100)
.tiType("так же незаметно, ")
.tiPause(400)
.tiType("как это лето. ")
.tiPause(1200)
.tiType("Наверное, ")
.tiPause(550)
.tiType("всему лучшему в нашей жизни суждено пролетать так быстро.").tiPause(1500)
.tiBreak()
.tiType("Сегодня твой праздник, ")
.tiPause(200)
.tiType("и мы от всей души хотим поздравить тебя!")
.tiPause(2000)
.tiBreak()
.tiBreak()
.tiType("Пускай в этот день мы не были рядом, ")
.tiPause(200)
.tiType("надеемся, что воспоминания, ")
.tiPause(200)
.tiType("навеянные этой игрой, ")
.tiPause(200)
.tiType("хотя бы немного приблизили нас к тебе. ")
.tiPause(400)
.tiType("Мы хотим пожелать, ")
.tiPause(200)
.tiType("чтобы ты никогда не чувствовал себя одиноким, ")
.tiPause(200)
.tiType("потому что мы всегда рядом с тобой вне зависимости от километров или обстоятельств. ")
.tiPause(400)
.tiType("Всегда стремись к успеху и добивайся поставленных целей!")
.tiPause(2000)
.tiBreak()
.tiBreak()
.tiType("Любим и скучаем,")
.tiPause(1000)
.tiBreak()
.tiType("Твои друзья  <i class=\"em em-heart\"></i>")
.tiPause(3000)
.tiBreak()
.tiType("<a href=\"https://vk.me/join/AJQ1d_z1HxQq0TPXaU65WSuE\">Присоединиться к беседе :)</a>")
.tiPause(3000)
.tiBreak()
.tiType("<a href=\"https://ilya18.me/reset\">Пройти игру ещё раз</a>")