let stages=["L3dlbGNvbWUv", 
            "L3F1aXovbWVsb2R5Lw==", 
            "L2NvZGVzL2lyay8=", 
            "L3AvbW9zY293Lw==", 
            "L3F1aXovaGlraW5nLw==", 
            "L2NvZGVzL21zay8=", 
            "L3Avc2FpbnQtcC8=", 
            "L3F1aXovY2F0Y2gv", 
            "L2NvZGVzL3NwYi8=", 
            "L2NvZGVzL3RvZ2V0aGVyLw==",
            "L2hhcHB5LWJkYXkv"]